/**
 * This package boosts programmer productivity by generating boilerplate XML.
 * 
 * Depending on the implemented interfaces of the package, XML is generated by the {@link dk.brics.jwig.boost.rendering.hierarchy.Renderer}. 
 */
package dk.brics.jwig.boost.rendering.hierarchy;